In [1]:
from google.colab import files
upload=files.upload()

Saving framingham.csv to framingham.csv

In [3]:
import pandas as pd
data=pd.read_csv('framingham.csv')
data

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [4]:
data.dtypes

male                 int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
TenYearCHD           int64
dtype: object

In [5]:
data.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [6]:
data.corr()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.028979,0.017352,0.197596,0.317930,-0.052506,-0.004546,0.005313,0.015708,-0.070322,-0.035989,0.057933,0.081672,-0.116620,0.006083,0.088428
age,-0.028979,1.000000,-0.165883,-0.213748,-0.192791,0.122995,0.057655,0.307194,0.101258,0.262131,0.394302,0.206104,0.135800,-0.012823,0.122256,0.225256
education,0.017352,-0.165883,1.000000,0.018532,0.008085,-0.010815,-0.035112,-0.081970,-0.038680,-0.023115,-0.129631,-0.062316,-0.137504,-0.054206,-0.035721,-0.054059
currentSmoker,0.197596,-0.213748,0.018532,1.000000,0.769690,-0.048938,-0.032988,-0.103260,-0.044295,-0.046562,-0.130230,-0.107746,-0.167650,0.062356,-0.056826,0.019456
cigsPerDay,0.317930,-0.192791,0.008085,0.769690,1.000000,-0.046134,-0.032707,-0.066146,-0.037067,-0.026320,-0.088780,-0.056632,-0.092856,0.075157,-0.058960,0.057884
BPMeds,-0.052506,0.122995,-0.010815,-0.048938,-0.046134,1.000000,0.117365,0.261187,0.052047,0.080558,0.254219,0.194227,0.100668,0.015233,0.051176,0.087489
prevalentStroke,-0.004546,0.057655,-0.035112,-0.032988,-0.032707,0.117365,1.000000,0.074830,0.006949,0.000067,0.057009,0.045190,0.025891,-0.017676,0.018431,0.061810
prevalentHyp,0.005313,0.307194,-0.081970,-0.103260,-0.066146,0.261187,0.074830,1.000000,0.077808,0.163993,0.696755,0.615751,0.301318,0.147261,0.086834,0.177603
diabetes,0.015708,0.101258,-0.038680,-0.044295,-0.037067,0.052047,0.006949,0.077808,1.000000,0.040278,0.111283,0.050329,0.087036,0.048994,0.617627,0.097317
totChol,-0.070322,0.262131,-0.023115,-0.046562,-0.026320,0.080558,0.000067,0.163993,0.040278,1.000000,0.208908,0.165182,0.115767,0.091125,0.046408,0.082184
sysBP,-0.035989,0.394302,-0.129631,-0.130230,-0.088780,0.254219,0.057009,0.696755,0.111283,0.208908,1.000000,0.784002,0.326981,0.182246,0.140621,0.216429
diaBP,0.057933,0.206104,-0.062316,-0.107746,-0.056632,0.194227,0.045190,0.615751,0.050329,0.165182,0.784002,1.000000,0.377588,0.181255,0.061231,0.145299
BMI,0.081672,0.135800,-0.137504,-0.167650,-0.092856,0.100668,0.025891,0.301318,0.087036,0.115767,0.326981,0.377588,1.000000,0.067678,0.087377,0.075192
heartRate,-0.116620,-0.012823,-0.054206,0.062356,0.075157,0.015233,-0.017676,0.147261,0.048994,0.091125,0.182246,0.181255,0.067678,1.000000,0.094500,0.022913
glucose,0.006083,0.122256,-0.035721,-0.056826,-0.058960,0.051176,0.018431,0.086834,0.617627,0.046408,0.140621,0.061231,0.087377,0.094500,1.000000,0.125544
TenYearCHD,0.088428,0.225256,-0.054059,0.019456,0.057884,0.087489,0.061810,0.177603,0.097317,0.082184,0.216429,0.145299,0.075192,0.022913,0.125544,1.000000

In [13]:
data['education']=data['education'].fillna(data['education'].mean())
data['cigsPerDay']=data['cigsPerDay'].fillna(data['cigsPerDay'].mean())
data['BPMeds']=data['BPMeds'].fillna(0)
data['totChol']=data['totChol'].fillna(data['totChol'].mean())
data['BMI']=data['BMI'].fillna(data['BMI'].mean())
data['heartRate']=data['heartRate'].fillna(data['heartRate'].mean())
data['glucose']=data['glucose'].fillna(data['glucose'].mean())

In [14]:
data.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   int64
 1   age              4238 non-null   int64
 2   education        4238 non-null   float64
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4238 non-null   float64
 5   BPMeds           4238 non-null   float64
 6   prevalentStroke  4238 non-null   int64
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4238 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4238 non-null   float64
 13  heartRate        4238 non-null   float64
 14  glucose          4238 non-null   float64
 15  TenYearCHD       4238 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 529.9 KB

In [16]:
data['BPMeds'].value_counts()

0.0    4114
1.0     124
Name: BPMeds, dtype: int64

In [17]:
data.corr()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.028979,0.017126,0.197596,0.316807,-0.051545,-0.004546,0.005313,0.015708,-0.069974,-0.035989,0.057933,0.081506,-0.116601,0.005818,0.088428
age,-0.028979,1.000000,-0.163613,-0.213748,-0.192366,0.120955,0.057655,0.307194,0.101258,0.260270,0.394302,0.206104,0.135283,-0.012819,0.116850,0.225256
education,0.017126,-0.163613,1.000000,0.018301,0.007962,-0.010363,-0.035110,-0.080993,-0.038146,-0.022507,-0.128260,-0.061755,-0.135635,-0.053626,-0.033721,-0.053384
currentSmoker,0.197596,-0.213748,0.018301,1.000000,0.766970,-0.048358,-0.032988,-0.103260,-0.044295,-0.046285,-0.130230,-0.107746,-0.167276,0.062348,-0.054157,0.019456
cigsPerDay,0.316807,-0.192366,0.007962,0.766970,1.000000,-0.045663,-0.032706,-0.065947,-0.037063,-0.026025,-0.088505,-0.056391,-0.092453,0.074851,-0.056088,0.057775
BPMeds,-0.051545,0.120955,-0.010363,-0.048358,-0.045663,1.000000,0.114609,0.258697,0.051394,0.078712,0.251503,0.192356,0.099647,0.015139,0.048856,0.086417
prevalentStroke,-0.004546,0.057655,-0.035110,-0.032988,-0.032706,0.114609,1.000000,0.074830,0.006949,0.000067,0.057009,0.045190,0.024840,-0.017676,0.018055,0.061810
prevalentHyp,0.005313,0.307194,-0.080993,-0.103260,-0.065947,0.258697,0.074830,1.000000,0.077808,0.163041,0.696755,0.615751,0.300572,0.147222,0.082924,0.177603
diabetes,0.015708,0.101258,-0.038146,-0.044295,-0.037063,0.051394,0.006949,0.077808,1.000000,0.040092,0.111283,0.050329,0.086250,0.048993,0.605705,0.097317
totChol,-0.069974,0.260270,-0.022507,-0.046285,-0.026025,0.078712,0.000067,0.163041,0.040092,1.000000,0.207609,0.163903,0.114789,0.090676,0.044583,0.081624
sysBP,-0.035989,0.394302,-0.128260,-0.130230,-0.088505,0.251503,0.057009,0.696755,0.111283,0.207609,1.000000,0.784002,0.325247,0.182174,0.134608,0.216429
diaBP,0.057933,0.206104,-0.061755,-0.107746,-0.056391,0.192356,0.045190,0.615751,0.050329,0.163903,0.784002,1.000000,0.376544,0.181246,0.058647,0.145299
BMI,0.081506,0.135283,-0.135635,-0.167276,-0.092453,0.099647,0.024840,0.300572,0.086250,0.114789,0.325247,0.376544,1.000000,0.067544,0.082109,0.074680
heartRate,-0.116601,-0.012819,-0.053626,0.062348,0.074851,0.015139,-0.017676,0.147222,0.048993,0.090676,0.182174,0.181246,0.067544,1.000000,0.089341,0.022898
glucose,0.005818,0.116850,-0.033721,-0.054157,-0.056088,0.048856,0.018055,0.082924,0.605705,0.044583,0.134608,0.058647,0.082109,0.089341,1.000000,0.120406
TenYearCHD,0.088428,0.225256,-0.053384,0.019456,0.057775,0.086417,0.061810,0.177603,0.097317,0.081624,0.216429,0.145299,0.074680,0.022898,0.120406,1.000000

In [10]:
data[data['BPMeds'].isnull()]

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
49,1,36,3.0,1,20.0,NaN,0,1,0,194.000000,139.0,93.0,24.33,80.0,62.000000,0
77,0,44,3.0,1,20.0,NaN,0,0,0,213.000000,115.0,72.5,21.16,80.0,89.000000,0
193,1,45,3.0,1,40.0,NaN,0,0,0,278.000000,135.0,84.0,23.79,75.0,79.000000,1
245,1,46,1.0,1,30.0,NaN,0,1,0,253.000000,147.0,85.0,30.62,100.0,75.000000,0
314,0,39,2.0,0,0.0,NaN,0,0,0,242.000000,113.0,85.0,25.54,85.0,104.000000,0
395,0,65,2.0,0,0.0,NaN,0,1,0,270.000000,165.0,98.0,21.66,62.0,92.000000,1
421,1,44,1.0,0,0.0,NaN,0,0,1,190.000000,122.0,81.0,36.12,70.0,143.000000,0
765,1,50,4.0,1,9.0,NaN,0,0,0,296.000000,119.0,90.0,23.55,75.0,69.000000,1
769,0,37,3.0,0,0.0,NaN,0,0,0,145.000000,105.0,73.0,23.44,58.0,80.000000,0
797,0,59,4.0,0,0.0,NaN,0,1,0,240.000000,195.0,118.0,23.82,80.0,73.000000,0
998,0,57,1.0,0,0.0,NaN,0,0,0,372.000000,122.0,80.0,21.02,65.0,81.000000,0
1002,1,60,1.0,0,0.0,NaN,0,1,0,191.000000,167.0,105.0,23.01,80.0,85.000000,0
1044,0,65,1.0,0,0.0,NaN,1,1,0,290.000000,144.0,64.0,21.41,58.0,145.000000,1
1104,1,57,4.0,0,0.0,NaN,0,1,0,195.000000,162.0,108.0,32.65,85.0,73.000000,0
1122,0,67,1.0,1,6.0,NaN,0,0,0,236.721585,120.0,67.0,32.77,86.0,81.966753,0
1177,0,55,1.0,0,0.0,NaN,0,1,0,325.000000,155.0,90.0,26.27,68.0,72.000000,1
1206,0,66,1.0,0,0.0,NaN,0,1,0,235.000000,151.0,91.0,30.86,78.0,87.000000,0
1284,1,41,1.0,1,15.0,NaN,0,0,0,198.000000,114.5,80.0,22.53,72.0,75.000000,0
1301,0,43,3.0,1,10.0,NaN,0,0,0,186.000000,111.0,82.0,23.22,75.0,82.000000,0
1566,1,58,1.0,1,30.0,NaN,0,0,0,200.000000,144.0,90.0,24.90,75.0,76.000000,0
1573,0,67,2.0,0,0.0,NaN,0,0,0,261.000000,117.0,63.0,22.55,75.0,83.000000,0
1616,0,41,1.0,0,0.0,NaN,0,0,0,179.000000,121.0,83.0,23.04,66.0,90.000000,0
1721,0,57,1.0,0,0.0,NaN,0,0,0,262.000000,129.0,75.0,23.67,70.0,95.000000,0
1857,1,56,1.0,1,20.0,NaN,0,0,0,191.000000,130.0,70.0,26.09,75.0,97.000000,0
1861,0,60,1.0,0,0.0,NaN,0,1,0,273.000000,176.0,84.0,22.17,66.0,79.000000,0
1913,1,51,1.0,0,0.0,NaN,0,0,0,166.000000,115.0,82.5,26.69,64.0,67.000000,0
1983,0,63,2.0,0,0.0,NaN,0,1,0,283.000000,164.0,86.0,24.64,80.0,82.000000,0
1985,0,59,1.0,1,3.0,NaN,0,1,0,201.000000,145.0,88.0,39.91,65.0,89.000000,0
1986,0,59,1.0,1,30.0,NaN,0,0,0,316.000000,110.0,70.0,19.83,80.0,74.000000,1
2002,0,59,1.0,1,20.0,NaN,0,0,0,225.000000,110.0,64.0,28.10,66.0,64.000000,0
2074,1,45,2.0,1,10.0,NaN,0,1,0,232.000000,136.0,85.0,30.29,70.0,66.000000,0
2120,0,61,1.0,0,0.0,NaN,0,0,0,218.000000,148.0,80.0,37.04,82.0,78.000000,0
2173,0,62,3.0,0,0.0,NaN,0,1,0,294.000000,139.0,78.0,21.11,85.0,79.000000,0
2181,0,56,1.0,1,9.0,NaN,0,1,0,320.000000,142.0,84.0,27.90,74.0,95.000000,1
2367,0,57,4.0,0,0.0,NaN,0,1,0,328.000000,181.0,112.5,27.05,85.0,94.000000,1
2608,0,52,1.0,0,0.0,NaN,0,1,0,252.000000,208.0,136.0,25.79,92.0,82.000000,0
2645,0,66,1.0,0,0.0,NaN,0,1,1,203.000000,205.0,83.0,28.27,75.0,118.000000,1
2738,0,68,1.0,0,0.0,NaN,0,1,0,258.000000,139.0,74.0,26.58,85.0,75.000000,1
2835,0,40,1.0,1,50.0,NaN,0,0,0,220.000000,124.0,79.0,20.70,90.0,57.000000,0
2943,0,56,2.0,0,0.0,NaN,0,0,0,220.000000,126.5,74.5,28.30,82.0,80.000000,1
3226,0,41,1.0,1,20.0,NaN,0,0,0,203.000000,120.0,70.0,21.26,80.0,63.000000,0
3313,0,52,3.0,1,9.0,NaN,0,0,0,275.000000,102.0,70.5,20.40,65.0,81.966753,0
3373,1,51,4.0,0,0.0,NaN,0,0,0,154.000000,98.0,66.0,22.86,63.0,82.000000,0
3375,0,68,2.0,0,0.0,NaN,0,0,0,257.000000,144.0,95.0,29.25,80.0,77.000000,0
3526,0,60,1.0,0,0.0,NaN,0,1,0,231.000000,174.0,110.0,25.05,85.0,82.000000,0
3644,1,55,1.0,1,3.0,NaN,0,0,0,246.000000,112.5,72.5,27.56,60.0,72.000000,0
3737,0,41,2.0,1,20.0,NaN,0,0,0,220.000000,126.0,78.0,20.70,86.0,79.000000,0
3791,1,54,4.0,1,30.0,NaN,0,1,0,234.000000,152.5,80.0,23.50,75.0,75.000000,0
3816,0,56,1.0,0,0.0,NaN,0,1,0,391.000000,126.0,84.0,24.83,80.0,78.000000,0
4008,0,40,2.0,0,0.0,NaN,0,0,0,157.000000,131.0,85.0,27.38,95.0,78.000000,0
4139,0,53,3.0,0,0.0,NaN,0,0,0,252.000000,122.5,75.5,25.29,75.0,71.000000,0
4162,0,47,3.0,1,9.0,NaN,0,0,0,221.000000,127.5,75.0,23.78,69.0,73.000000,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.000000,131.0,72.0,22.00,84.0,86.000000,0